system/system/urls.py
from django.contrib import admin
from django.urls import path
from system_db import views

urlpatterns = [
    path('', views.index),
    path('actual', views.actual, name='actual'),
    path('szi', views.actual, name='dbSzi'),
    path('teplo', views.actual, name='dbTeplo'),
    path('admin/', admin.site.urls),

]

system/system_db/models.py
import datetime
from django.db import models

# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)

    def __repr__(self):
        return f'<Пользователь {self.name} {self.surname}>'


class Product(models.Model):
    name = models.CharField(max_length=128)
    objects = models.Manager()

    def __repr__(self):
        return f'<Изделие {self.name}>'


class Status(models.Model):
    name = models.CharField(max_length=30)
    style_class = models.TextField()
    icon = models.TextField(default='')
    object = models.Manager()

    def __repr__(self):
        return f'<Статус {self.name}>'


class Label(models.Model):
    name = models.CharField(max_length=30)
    style_class = models.TextField()
    object = models.Manager()


class ActualOrder(models.Model):
    product_id = models.ForeignKey(Product,
                                   on_delete=models.DO_NOTHING)
    count = models.IntegerField(default=0)
    # label = models.ForeignKey(Label, on_delete=models.DO_NOTHING, default=None)
    date = models.DateField()
    status = models.ForeignKey(Status,
                               on_delete=models.DO_NOTHING)
    note = models.TextField(default='')
    objects = models.Manager()

    def __repr__(self):
        return f'<Актуальный заказ №{self.id}>'

system/system_db_invoice/models.py
from django.db import models

# Create your models here.


# class User(models.Model):
#     name = models.CharField()
#     surname = models.CharField()
#
#
# class Product(models.Model):
#     name = models.CharField()
#
#
# class Status(models.Model):
#     name = models.CharField()
#     style_class = models.CharField()
#
#
# class Actual_order(models.Model):
#     number = models.CharField()
#     product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
#     status = models.CharField(Status, on_delete=models.CASCADE)

system/system_db/forms.py
from django import forms
from .models import *


class UserForm(forms.Form):
    name = forms.CharField(label='Имя клиента')
    age = forms.IntegerField(label='Возраст')


def prod():
    x = [(x.id, x.name) for x in Product.objects.all()]
    x.insert(0, ('0', 'Выбрать...'))
    return tuple(x)


class AddOrder(forms.Form):
    product = forms.ChoiceField(label='Выберать изделие',
                                choices=prod(),
                                widget=forms.Select(attrs={'class': 'form-select mb-2 js-chosen'}))
    count = forms.IntegerField(label='Количество',
                               min_value=1,
                               max_value=1000,
                               widget=forms.NumberInput(attrs={'class': 'form-control mb-2'}))
    # label = forms.ChoiceField(choices=tuple((x.id, x.name) for x in Label.object.all()))
    date = forms.DateField(label='Желаемая дата готовности',
                           widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control mb-2'}),
                           initial=datetime.date.today().strftime('%Y-%m-%d'))
    note = forms.CharField(label='Примечание',
                           required=False,
                           widget=forms.TextInput(attrs={'class': 'form-control mb-2'}))
    status = forms.IntegerField(widget=forms.HiddenInput, initial=1)

system/system_db/views.py
from django.shortcuts import render
from django.http import *
from .forms import UserForm, AddOrder
from .models import *
from datetime import datetime


# Create your views here.


def index(request):
    return render(request, "index.html", {'form': UserForm()})


def actual(request):
    if request.method == 'GET':
        return render(request, 'actual.html', {'form': AddOrder(),
                                               'orders': ActualOrder.objects.all(),
                                               'status': Status.object.all(),
                                               'main': 'actual'})
    elif request.method == 'POST':
        action = request.POST.get('action')
        res = {'scs': False, 'msg': 'Ошибка действия'}

        if action == 'add' or action == 'edit':

            post_data = dict(product_id=Product.objects.get(id=int(request.POST.get('product'))) if request.POST.get('product') else None,
                             count=int(request.POST.get('count')) if request.POST.get('count') else None,
                             date=datetime.strptime(request.POST.get('date'), '%Y-%m-%d') if request.POST.get('date') else None,
                             status=Status.object.get(id=request.POST.get('status')) if request.POST.get('status') else None,
                             note=request.POST.get('note') if request.POST.get('note') else None)
            values_for_update = {k: v for k, v in post_data.items() if v is not None}

            if len(values_for_update.keys()) > 0:

                order, created = ActualOrder.objects.update_or_create(id=request.POST.get('id'),
                                                                      defaults=values_for_update)
                res['scs'] = True
                res['msg'] = f'Новый заказ №{order.id} добавлен' if created else f'Заказ №{order.id} обновлен'
                res['order'] = {'id': order.id,
                                'product': order.product_id.name,
                                'count': str(order.count)+' шт.',
                                'date': order.date.strftime('%d.%m.%Y'),
                                'status': {
                                    'name': order.status.name,
                                    'class': order.status.style_class,
                                    'icon': order.status.icon
                                },
                                'note': order.note}

            else:
                res['scs'] = True
                res['msg'] = 'Ничего не произошло'
        # elif action == 'edit':

        elif action == 'delete':
            ActualOrder.objects.filter(id=request.POST.get('id')).delete()
            res['msg'] = f'Актуальный заказ №{request.POST.get("id")} удален'
            res['scs'] = True
        return JsonResponse(res)
    else:
        return HttpResponseNotAllowed('<h2>Ошибка</h2>')




def db_szi(request):
    pass

system/templates/actual.html
{% extends "base.html" %}
{% block title %}Актуальные заказы{% endblock title %}

{% block content %}
<div class="row" xmlns="http://www.w3.org/1999/html">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right" style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="#">Главная</a></li>
                        <li class="breadcrumb-item active">Актуальные заказы</li>
                    </ol>
                </div>
                <h4 class="page-title">Таблица актуальных заказов</h4>
            </div>
        </div>
    </div>
    <div class="card border-0 shadow-sm">
        <div class="card-body" style="padding: 1.5rem!important;">
            <div class="row mb-2">
                <div class="col-7 d-flex">
                    <div class="d-flex align-items-center">
                        <label class="me-2">Статус:</label>
                        <select id="sort_status" class="form-select" style="width: auto">
                            <option value="0" selected>Все</option>
                            {% for st in status %}
                                <option value="{{ st.id }}">{{ st.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-5 text-sm-end">
                    <button id="add" class="btn btn-primary">Добавить</button>
                    <button id="filter" class="btn btn-light"><i class="bi bi-filter"></i></button>
                    <button id="ex" class="btn btn-light">Экспорт</button>
                </div>
            </div>
            <table id="table_actual_order" class="table">
                <thead class="table-light">
                <tr>
                    <th style="width:1%"><input type="checkbox" class="form-check-input"></th>
                    <th style="width:13%">Наименование</th>
                    <th style="width:10%">Количество</th>
                    <th style="width:17%">Желаемая дата готовности</th>
                    <th style="width:15%">Состояние готовности</th>
                    <th style="width:25%">Примечание</th>
                    <th class="text-end" style="width:7%">Действия</th>
                </tr>
                </thead>
                <tbody class="table-hover">
                {% for order in orders %}
                <tr id="{{ order.id }}">
                    <td><input type="checkbox" class="form-check-input"></td>
                    <td class="product">{{ order.product_id.name }}</td>
                    <td class="count">{{ order.count }} шт.</td>
                    <td class="date">{{ order.date|date:"d.m.Y" }}</td>
                    <td class="status" val-status="{{order.status.id}}"><span class="badge {{ order.status.style_class }}">{{ order.status.icon|safe }} {{ order.status.name }}</span></td>
                    <td class="note">{{ order.note }}</td>
                    <td class="action text-end">
                        <i class="fa-regular fa-pen-to-square" title="Редактировать"></i>
                        <i class="fa-regular fa-trash-can" title="Удалить запись"></i>
                    </td>
                </tr>

                {% empty %}
                <tr id="no_row"><td colspan="7">В базе нет актуальных заказов</td></tr>
                {% endfor %}
                </tbody>
            </table>
            <div id="add_layer" class="d-none">
                <form id="add_form" class="form col-4">
                    {{ form }}
                    <button type="submit" class="btn btn-success mt-2">Добавить</button>
                </form>
            </div>
        </div>


    </div>
{% endblock content %}


{% block script %}

    $('#add').on('click', function() {
        $('#add_layer').toggleClass('d-none')
    });

    $('#add_form').on('submit', function(e) {
        e.preventDefault();
        var data = 'action=edit&' + $(this).serialize()
        if ($('tr#no_row')) {
            $('tr#no_row').remove()
        }

        $.ajax({
            url: '/actual',
            type: 'POST',
            data: csrf + data,
            success: function(res) {
                if (res.scs) {
                    $('#table_actual_order tbody').prepend('<tr id="'+ res.order.id+'">' +
                                                            '<td><input type="checkbox"></td>'+
                                                            '<td class="product">'+res.order.product+'</td>'+
                                                            '<td class="count">'+res.order.count+'</td>'+
                                                            '<td class="date">'+res.order.date+'</td>'+
                                                            '<td class="status"><span class="badge '+res.order.status.class+'">'+res.order.status.icon+res.order.status.name+'</span></td>'+
                                                            '<td class="note">'+res.order.note+'</td>'+
                                                            '<td class="action text-end"><i class="fa-regular fa-pen-to-square" title="Редактировать"></i>'+
                                                                '<i class="fa-regular fa-trash-can" title="Удалить запись"></i></td>'+
                                                            '</tr>')
                } else {
                    console.log('error on server side');
                }
            },
            error: function(request,msg,error) {
                error_msg(request,msg,error)
            }
        })
        $(this).trigger("reset");

    });


    $('#table_actual_order').on('click', '.row_delete', function(e) {
        e.preventDefault();
        var id_row = $(this).parent().parent().attr('id')
        var data = 'action=delete&id=' + id_row

        $.ajax({
            url: '/actual',
            type: 'POST',
            data: csrf + data,
            success: function(res) {
                if (res.scs) {
                    $('tr#'+id_row).remove();
                    if (!$('#table_actual_order tbody').find('tr').length) {
                        $('#table_actual_order tbody').append('<tr id="no_row"><td colspan="7">В базе нет актуальных заказов</td></tr>')
                    }
                } else {
                    console.log('error on server side');
                }
            },
            error: function(request,msg,error) {
                error_msg(request,msg,error)
            }
        })
    });

    $('#table_actual_order').on('click', '.fa-pen-to-square', function(){

        var id_row = $(this).parent().parent().attr('id')

        $(this).toggleClass('fa-pen-to-square')
        $(this).toggleClass('fa-circle-check active')
        $(this).attr('title', 'Внести изменения')

        var opt_prod = $('#id_product').html()
        var opt_stat = $('#sort_status').html()
        $('table#table_actual_order tbody tr#'+id_row+' td:eq(1)').append('<br><br><select name="product" class="form-select mb-2">' + opt_prod + '</select>')
        $('table#table_actual_order tbody tr#'+id_row+' td:eq(2)').append('<br><br><div class="input-group"><input type="number" name="count" class="form-control mb-2" min="1" max="1000" required="">'+
                                                                            '<span class="input-group-text mb-2">шт.</span></div>')
        $('table#table_actual_order tbody tr#'+id_row+' td:eq(3)').append('<br><br><input type="date" name="date" class="form-control mb-2" required="">')
        $('table#table_actual_order tbody tr#'+id_row+' td:eq(4)').append('<br><br><select name="status" class="form-select mb-2">' + opt_stat + '</select>')
        $('table#table_actual_order tbody tr#'+id_row+' td:eq(5)').append('<br><br><input type="text" name="note" class="form-control mb-2 col">')
        $('table#table_actual_order tbody tr#'+id_row+' td:eq(6) .fa-circle-check').after('<i class="fa-solid fa-ban" title="Отменить редактирование"></i>')


    });



    $('#table_actual_order').on('click', '.fa-circle-check', function(){
        var id_row = $(this).parent().parent().attr('id')
        var data = 'action=edit&id='+id_row
        if ($('#table_actual_order tr#'+id_row+' td:eq(1) select').val() != '0') {
            data += '&product=' + $('#table_actual_order tr#'+id_row+' td:eq(1) select').val()
        }
        if ($('#table_actual_order tr#'+id_row+' td:eq(2) input').val() != '') {
            data += '&count=' + $('#table_actual_order tr#'+id_row+' td:eq(2) input').val()
        }
        if ($('#table_actual_order tr#'+id_row+' td:eq(3) input').val() != '') {
            data += '&date=' + $('#table_actual_order tr#'+id_row+' td:eq(3) input').val()
        }
        if ($('#table_actual_order tr#'+id_row+' td:eq(4) select').val() != '0') {
            data += '&status=' + $('#table_actual_order tr#'+id_row+' td:eq(4) select').val()
        }
        if ($('#table_actual_order tr#'+id_row+' td:eq(5) input').val() != '') {
            data += '&note=' + $('#table_actual_order tr#'+id_row+' td:eq(5) input').val()
        }

        $.ajax({
            url: '/actual',
            type: 'POST',
            data: csrf + data,
            success: function(res) {
                if (res.scs) {
                    console.log('ok!', res.msg);
                    var k = Object.keys(res.order)
                    console.log(k,k.lenght);
                    for (var i = 0; i < k.length; i++) {
                        console.log($('tr#'+res.order.id+' td.'+k[i]));
                        if (k[i] == 'status') {
                            $('tr#'+res.order.id+' td.'+k[i]).html('<span class="badge '+res.order.status.class+'">'+res.order.status.icon+ ' ' +res.order.status.name+'</span>')
                        } else {
                            $('tr#'+res.order.id+' td.'+k[i]).html(res.order[k[i]])
                        }
                       // ещё какие-то выражения
                    }

                } else {
                    console.log('error on server side');
                }
            },
            error: function(request,msg,error) {
                error_msg(request,msg,error)
            }
        })

    });
    $('#table_actual_order').on('click', '.fa-ban, .fa-circle-check', function(){

        $('.fa-circle-check').toggleClass('fa-pen-to-square')
        $('.fa-circle-check').toggleClass('fa-circle-check active')
        var id_row = $(this).parent().parent().attr('id')

        $('table#table_actual_order tbody tr#'+id_row).find('select, input[type!="checkbox"], br, .input-group, .fa-ban').remove()
        $('.fa-pen-to-square').attr('title', 'Редактировать')
    });


    $('#sort_status').on('change', function() {
        console.log($(this).val())
        if ($(this).val() == '0') {
            $('tbody').find('tr').removeClass('d-none')
        } else {
            $('tbody').find('tr').addClass('d-none')
            $('tr td[val-status="'+$(this).val()+'"]').parent().removeClass('d-none')

        }

    });

{% endblock %}

system/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="ru">
<head>
    <meta charset="UТF-8">
    <link href="{% static 'images/favicon.ico' %}" rel="icon">
    <title>{% block title %}Заголовок{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>
<body style="min-height: 100vh;background-color:#f9fbfe;">

    <div class="container-fluid" style="min-height:100vh">
        <div class="row p-0" style="min-height:100vh">
            {# Боковое меню #}
            <nav id="sidebarMenu" class="nav flex-column sidebar navbar-dark" style="width: 17%;color:white!important;background:#313a46">
                <a href="index.html" class="logo text-center logo-light" style="line-height: 8em;">
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-white.png' %}" alt="" height="24">
                    </span>
                </a>
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column navbar-nav nav-pills">
                        <li class="nav-item px-2 px-lg-4">
                            <a class="nav-link" aria-current="page" href="#">
                                Счета
                            </a>
                        </li>
                        <li class="nav-item px-2 px-lg-4">
                            <a class="nav-link" aria-current="page" href="{% url 'actual' %}">
                                Актуальные заказы
                            </a>
                        </li>
                        <li class="nav-item px-2 px-lg-4">
                            <a class="nav-link" aria-current="page" href="/bd-szi">
                                База средств защиты информации
                            </a>
                        </li>
                        <li class="nav-item px-2 px-lg-4">
                            <a class="nav-link" aria-current="page" href="/bd-teplo">
                                База тепловизоров
                            </a>
                        </li>
                        <li class="nav-item px-2 px-lg-4">
                            <a class="nav-link" aria-current="page" href="/stat">
                                Статистика
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>
            <div style="width: 83%;margin-left: auto!important;padding:0;">
                <header class="navbar navbar-light sticky-top bg-white flex-md-nowrap p-0 py-3 shadow-sm">
                    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <form class="form-inline col-4 ml-auto h-100 px-3">
                        <div class="input-group w-100 h-100">
                            <input class="form-control form-control-dark" type="search" placeholder="Поиск" aria-label="Поиск" aria-describedby="button-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-danger" type="submit" id="button-addon2">Поиск</button>
                            </div>
                        </div>
                    </form>
                    <div class="navbar-nav" style="flex-direction: row">
                        {% if current_user.is_anonymous %}
                        <div class="nav-item text-nowrap">
                            <a class="nav-link px-3" href="">Вход<i class="bi bi-box-arrow-in-right ml-2"></i></a>
                        </div>
                        {% else %}
                        <div class="nav-item text-nowrap">
                            <a class="nav-link px-3" href="">Профиль<i class="bi bi-person-circle ml-2"></i></a>
                        </div>
                        <div class="nav-item text-nowrap">
                            <a class="nav-link px-3" href="">Выйти<i class="bi bi-box-arrow-right ml-2"></i></a>
                        </div>
                        {% endif %}
                    </div>
                </header>
                <main class="p-3 container-fluid">
                    {% block content%}

                    {% endblock content %}
                </main>
<!--                <footer class="footer fixed-bottom">-->
<!--                    <div class="container-fluid">-->
<!--                        <div class="row">-->
<!--                            <div class="col-md-6">-->
<!--                                <script>document.write(new Date().getFullYear())</script> © Лаборатория ППШ-->
<!--                            </div>-->
<!--                            <div class="col-md-6">-->
<!--                                <div class="text-md-end footer-links d-none d-md-block">-->
<!--                                    <a href="#">About</a>-->
<!--                                    <a href="#">Support</a>-->
<!--                                    <a href="#">Contact Us</a>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </footer>-->
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/b36b9d0102.js" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function(){
            var csrf = 'csrfmiddlewaretoken={{ csrf_token }}&'

            function error_msg (req,msg,err) {
                console.log(req,msg,error)
            }
            {% if main %}
            $('a[href="/{{main}}"]').parent().addClass('main')
            {% endif %}

            {% block script %}
            {% endblock %}
        });
    </script>
</body>
</html>

system/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock title %}
{% block header %}Главная страница{% endblock header %}
{% block content %}
    Связка шаблонов index.html и base.html
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock content %}